import { toAdifBand } from '../bands.ts';
import { isStatsEligible } from '../pota-stats.ts';
import type { Qso } from '../types.ts';

function field(name: string, value: string): string {
  return `<${name}:${value.length}>${value}`;
}

// Guide section 4.3's field table: CALL/QSO_DATE/TIME_ON/BAND/MODE/
// STATION_CALLSIGN/OPERATOR are required for every club QSO; MY_SIG/
// MY_SIG_INFO ("POTA"/our park) are always present; SIG/SIG_INFO ("POTA"/
// their park) are present only for a park-to-park contact. RST_SENT/
// RST_RCVD/STATE aren't in the guide's table but are standard log fields
// and what's actually exchanged on air in the guide's own example QSO.
// `includePotaFields` is false for the personal QRZ/LoTW export (see
// toPersonalAdifLog below) -- MY_SIG/MY_SIG_INFO/SIG/SIG_INFO are POTA
// submission bookkeeping, not something to replay into a general logbook.
function toAdifRecord(q: Qso, clubCall: string, includePotaFields: boolean): string {
  const date = q.ts.slice(0, 10).replace(/-/g, '');
  const time = q.ts.slice(11, 19).replace(/:/g, '');

  const parts = [
    field('CALL', q.call),
    field('QSO_DATE', date),
    field('TIME_ON', time),
    field('BAND', toAdifBand(q.band)),
    field('MODE', q.mode),
    field('STATION_CALLSIGN', clubCall),
    field('OPERATOR', q.operatorCall),
    field('RST_SENT', q.rstSent),
    field('RST_RCVD', q.rstRcvd),
  ];
  if (q.theirState) parts.push(field('STATE', q.theirState));
  if (includePotaFields) {
    parts.push(field('MY_SIG', 'POTA'), field('MY_SIG_INFO', q.myPark));
    if (q.theirPark) parts.push(field('SIG', 'POTA'), field('SIG_INFO', q.theirPark));
  }
  return parts.join(' ') + ' <EOR>';
}

function adifHeader(): string[] {
  return ['Generated by PigletParkPounder', field('ADIF_VER', '3.1.4'), field('PROGRAMID', 'PigletParkPounder'), '<EOH>'];
}

export function toAdifLog(qsos: readonly Qso[], clubCall: string): string {
  const eligible = qsos.filter(isStatsEligible);
  const sorted = [...eligible].sort((a, b) => a.ts.localeCompare(b.ts));
  const lines = [...adifHeader(), ...sorted.map((q) => toAdifRecord(q, clubCall, true))];
  return lines.join('\n') + '\n';
}

// A single operator's own copy of the QSOs they made, for their personal
// logbook (QRZ, LoTW, etc.) -- not a second POTA submission. POTA credit for
// the operator already flows automatically once the club uploads its own
// log (guide section 6), so this deliberately omits the POTA SIG fields;
// re-submitting those under the operator's own account would be wrong
// (guide section 6: "DO NOT upload copies of the log ... to your personal
// account").
export function toPersonalAdifLog(qsos: readonly Qso[], clubCall: string, operatorCall: string): string {
  const eligible = qsos.filter((q) => isStatsEligible(q) && q.operatorCall === operatorCall);
  const sorted = [...eligible].sort((a, b) => a.ts.localeCompare(b.ts));
  const lines = [...adifHeader(), ...sorted.map((q) => toAdifRecord(q, clubCall, false))];
  return lines.join('\n') + '\n';
}

export interface AdifSubmissionGroup {
  park: string;
  state?: string;
  dateUtc: string;
  filename: string;
  content: string;
}

// Guide section 5: submissions are "1 log per park and state", filed as
// <clubcall>@<park>-<yyyymmdd>.adi. Splits the log into exactly that
// grouping so the Captain can download one file per required submission.
export function groupForSubmission(qsos: readonly Qso[], clubCall: string): AdifSubmissionGroup[] {
  const eligible = qsos.filter(isStatsEligible);
  const groups = new Map<string, Qso[]>();

  for (const q of eligible) {
    const dateUtc = q.ts.slice(0, 10);
    const key = `${q.myPark}|${q.myState ?? ''}|${dateUtc}`;
    const list = groups.get(key);
    if (list) list.push(q);
    else groups.set(key, [q]);
  }

  const parsed = [...groups.entries()].map(([key, list]) => {
    const [park, state, dateUtc] = key.split('|') as [string, string, string];
    return { park, state: state || undefined, dateUtc, list };
  });

  // A park spanning state lines (guide section 7.1) produces more than one
  // group for the same park+day, differentiated only by state -- the
  // guide's plain <clubcall>@<park>-<yyyymmdd>.adi convention can't tell
  // those apart, so fall back to appending the state whenever two groups
  // would otherwise collide on the same filename.
  const baseNameCounts = new Map<string, number>();
  for (const g of parsed) {
    const base = `${clubCall}@${g.park}-${g.dateUtc.replace(/-/g, '')}`;
    baseNameCounts.set(base, (baseNameCounts.get(base) ?? 0) + 1);
  }

  return parsed
    .map(({ park, state, dateUtc, list }) => {
      const base = `${clubCall}@${park}-${dateUtc.replace(/-/g, '')}`;
      const filename = (baseNameCounts.get(base) ?? 0) > 1 ? `${base}-${state ?? 'NOSTATE'}.adi` : `${base}.adi`;
      return { park, state, dateUtc, filename, content: toAdifLog(list, clubCall) };
    })
    .sort((a, b) => a.filename.localeCompare(b.filename));
}
